version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: thiago
      POSTGRES_PASSWORD: Thiago2023
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
